# Generated by Django 5.1.4 on 2025-01-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('meal_type', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=0, max_digits=4)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=3)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
