# Generated by Django 5.1.4 on 2025-01-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
