# Generated by Django 5.1.4 on 2025-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlog', '0002_alter_food_calories_alter_food_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
