# Generated by Django 5.1.4 on 2025-01-13 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 15, 27, 18, 588802, tzinfo=datetime.timezone.utc)),
        ),
    ]
